"""Snapshot test: docs/report-sample.md must stay byte-identical to a fresh
render of the demo fixture.

The golden sample is regenerated by scripts/make_golden_sample.py; this test is
the guard that keeps the committed doc from drifting away from actual tool
output (the failure it exists to catch: symptoms.yaml/renderer edits that
silently change what a "correct" report looks like).
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).parents[1]


def _load_golden_module():
    spec = importlib.util.spec_from_file_location(
        "make_golden_sample", REPO_ROOT / "scripts" / "make_golden_sample.py"
    )
    module = importlib.util.module_from_spec(spec)
    sys.modules["make_golden_sample"] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def golden():
    return _load_golden_module()


def _doc_region(golden) -> str:
    doc = golden.GOLDEN_DOC.read_text(encoding="utf-8")
    start = doc.index(golden.MARKER_START) + len(golden.MARKER_START)
    end = doc.index(golden.MARKER_END)
    return doc[start:end].strip()


def test_committed_golden_matches_fresh_render(golden):
    """If this fails, run: python scripts/make_golden_sample.py"""
    assert _doc_region(golden) == golden.render_golden_body()


def test_render_is_deterministic(golden):
    assert golden.render_golden_body() == golden.render_golden_body()


def test_all_six_sections_present(golden):
    body = _doc_region(golden)
    for section in ("一、总体诊断", "二、量化指标", "三、病症发作记录",
                    "四、情绪心电图", "五、处方建议", "六、免责声明"):
        assert section in body


def test_composite_score_is_reproducible(golden):
    """The headline number stays pinned to the documented value."""
    assert "综合评分：40 / 100" in _doc_region(golden)
